package com.ecru.clothing.dto.request;

import lombok.Data;

@Data
public class PinduoduoImportPreviewRequest {

    /**
     * Supported values: structured_json, har, html, auto.
     */
    private String mode;

    /**
     * Raw payload pasted from the browser, HTML source, HAR JSON, or the output
     * generated by the browser-side extractor script.
     */
    private String payload;

    /**
     * When true, only clothing-like items are returned in the preview.
     */
    private Boolean onlyClothing;
}
